# Generated by Django 5.2.7 on 2025-10-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Authentication Log', 'verbose_name_plural': 'Authentication Logs'},
        ),
    ]
